[tool.poetry]
name = "hub"
version = "0.1.0"
description = ""
authors = ["mkinf <info@mkinf.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
ddg_search = { path = "./langchain/ddg_search", develop = true }
fastapi = "^0.115.5"
uvicorn = "^0.32.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
